version: "3.3"

services:

  jenkins:
    image: jenkins/jenkins:2.504
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - ./jenkins:/var/jenkins_home
    restart: unless-stopped
    # depends_on:
    #   - gitlab

  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    hostname: gitlab.example.com
    ports:
    - "8070:80"
    - "2224:22"
    volumes:
    - ./gitlab/config:/etc/gitlab
    - ./gitlab/logs:/var/log/gitlab
    - ./gitlab/data:/var/opt/gitlab
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     external_url 'http://gitlab.example.com:8081'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 2224
    shm_size: '256m'

  mails:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
    - "8025:8025"
    - "1025:1025"
